/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static Logica.GestorArchivo.LongitudesCampos;
import com.csvreader.CsvWriter;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jeffer
 */
public class EdicionCampo extends javax.swing.JDialog {

    public String nombreArchivo;
    public JScrollPane PanelTabla;
    public ArrayList <String> lineas= new ArrayList<>();
    //public String nombreCampo;
    /**
     * Creates new form NewJDialog
     */
    public EdicionCampo(java.awt.Frame parent, boolean modal, String nombreArchivo, JScrollPane jScrollPane1) {
        super(parent, modal);
        this.nombreArchivo = nombreArchivo;
        this.PanelTabla = jScrollPane1;
        //this.nombreCampo = campo;
        initComponents();
        setLocationRelativeTo(null);
        btnEditarNombre.setEnabled(false);
        btnEditarLongitud.setEnabled(false);
        txtEditarNombre.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombreCampo = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        labelito = new javax.swing.JLabel();
        txtEditarNombre = new javax.swing.JTextField();
        btnEditarNombre = new javax.swing.JButton();
        btnEditarLongitud = new javax.swing.JButton();

        jPanel1.setForeground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 102, 255));

        jPanel2.setBackground(new java.awt.Color(153, 102, 255));

        jLabel1.setText("Ingrese el nombre del campo que desea editar:");

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        labelito.setText("Ingrese los datos de acuerdo al boton que desea presionar:");

        btnEditarNombre.setText("Editar Nombre");
        btnEditarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarNombreActionPerformed(evt);
            }
        });

        btnEditarLongitud.setText("Editar Longitud");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(txtNombreCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(btnEditarNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditarLongitud)
                .addGap(85, 85, 85))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtEditarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(labelito, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreCampo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEditarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarNombre)
                    .addComponent(btnEditarLongitud))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        boolean ban = false;
        System.out.println(nombreArchivo);
        for (int i = 0; i < LongitudesCampos.size(); i++) {
            if (LongitudesCampos.get(i).getCamp().equals(txtNombreCampo.getText()) && LongitudesCampos.get(i).getNombre().equals(nombreArchivo)) {

                btnEditarNombre.setEnabled(true);
                btnEditarLongitud.setEnabled(true);

                txtEditarNombre.setEnabled(true);
                ban = true;
            }
        }
        if (ban == false) {
            JOptionPane.showMessageDialog(null, "No se ha encontrado ninguna coincidencia");
            btnEditarNombre.setEnabled(false);
            btnEditarLongitud.setEnabled(false);
            txtEditarNombre.setEnabled(false);

        } else if (ban == true) {
            System.out.println("verdadero");

        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEditarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarNombreActionPerformed
        // TODO add your handling code here:
        String texto = txtEditarNombre.getText();
        if (texto.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Escriba el nuevo nombre o longuitod del campo a editar");
        } else {
            try {
                String line = null;
                String[] campos;
                RandomAccessFile file = new RandomAccessFile("archivos/" + nombreArchivo + ".csv", "rw");
                line = file.readLine();
                campos = line.split(",");
                int longitud = 0;
                while (longitud < campos.length) {
                    if (campos[longitud].equals(txtNombreCampo.getText())) {
                        campos[longitud] = txtEditarNombre.getText();
                        longitud++;
                    }
                    longitud++;
                }
                longitud = 0;
                file.seek(0);
                while (longitud < campos.length) {
                    if (longitud == campos.length - 1) {
                        file.write(campos[longitud].getBytes());
                        longitud++;
                    } else {
                        file.write(campos[longitud].getBytes());
                        file.write(",".getBytes());
                        longitud++;
                    }
                }
                file.close();
                line = null;
                String newLine = null;
                //String[] camposmeta;
                String aux = new String();
                int band=0;
                RandomAccessFile fileMeta = new RandomAccessFile("archivos/META_BD.csv", "rw");
                
         
         FileReader fr = new FileReader ("archivos/META_BD.csv");
         BufferedReader br = new BufferedReader(fr);

         
          line="";
          
          long pointerAnt = fileMeta.getFilePointer();
            long pointerAct;
            
            
         while((line=br.readLine())!=null){
                                     
                    
                    if (line.contains(nombreArchivo) && line.contains(txtNombreCampo.getText())) {
                
                                newLine= line.replaceAll(txtNombreCampo.getText(), txtEditarNombre.getText());
                
                        aux=aux+newLine+"\n";
                
                    }else{
                        
                        aux=aux+line+"\n";
                        
                              
                    }
                }
                fileMeta.close();
                br.close();
                fr.close();
                RandomAccessFile fileNew = new RandomAccessFile("archivos/META_BD.csv", "rw");
                fileNew.seek(0);
                fileNew.writeBytes(aux);
                fileNew.close();
                
            for (int i = 0; i < LongitudesCampos.size(); i++) {

                if (LongitudesCampos.get(i).getCamp().equals(txtNombreCampo.getText()) && LongitudesCampos.get(i).getNombre().equals(nombreArchivo)) {
                    LongitudesCampos.get(i).setCamp(txtEditarNombre.getText());
                }
            }
            Principal pr= new Principal();
            pr.generarTabla();
            pr.setVisible(true);
            this.setVisible(false);
            JOptionPane.showMessageDialog(null, "Edicion Exitosa");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(EdicionCampo.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(EdicionCampo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnEditarNombreActionPerformed
    public void actualizarTabla(String campos) {
    
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEditarLongitud;
    private javax.swing.JButton btnEditarNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelito;
    private javax.swing.JTextField txtEditarNombre;
    public javax.swing.JTextField txtNombreCampo;
    // End of variables declaration//GEN-END:variables
}
